### ISSUE TITLE
Screen share error

### ISSUE THREAD

**Issue by TorchwoodPL** [scivision/PyLivestream#16]
Hi,

when I try to stream my screen on ubuntu 16 xfce I only get back screen. How can I fix that and where to search for a problem?

**Comment by scivision** [comment]
In general since this program generates command lines that are run by FFmpeg, I would try just using FFmpeg by itself to write to a video file.
This is a known issue with Wayland, but it seems you probably aren't running Wayland but instead X11.
[FFmpeg Desktop capture docs](https://trac.ffmpeg.org/wiki/Capture/Desktop)
