### ISSUE TITLE
stream from rtsp

### ISSUE THREAD

**Issue by arnauldb** [scivision/PyLivestream#2]
Hello,

can I stream from a rtsp adress?

Thank you,

**Comment by scivision** [comment]
I think you can, with `ffmpeg -i "rtsp://1.2.3.4"` as the beginning, where 1.2.3.4 is the IP address of your RTSP streaming source.

Which site are you wanting to stream to? E.g. YouTube Live, Periscope, Facebook Live...?

**Comment by arnauldb** [comment]
Currently, I stream ( a raspberry pi+camera/ that records birds in my garden) to youtube using a script that takes a rtsp stream from the Pi. I found your "ffmpeg-youtube-live" today, and will try it this week. I wish to be able to stream audio/video and easily switch between youtube/Periscope...

Or maybe I could install "ffmpeg-youtube-live" directly on the Pi (where is already installed Pikrellcam, an audio/video recording motion detect program  https://billw2.github.io/pikrellcam/pikrellcam.html)...

**Comment by scivision** [comment]
That sounds like a great idea. I would install on the Pi by `git clone` and `pip install -e .` so that in the future you can `git pull` any changes.

Basically I use this Python script instead of copying and pasting long Bash lines, I would need several for my various tasks. Instead I just remember to run a particular Python script. All these scripts due is "compute" a command line for the particular task.

OK so I think you have PiCam->Pi->RTSP->Youtube, and the GPU on the Pi is fast enough for X264 and this task.
Periscope uses a lower quality stream (lower bitrate) so *prima facie* I think that Periscope should work just as well.
Currently Periscope allows two different resolutions, with the same maximum bitrate.
If the Raspi CPU/GPU can handle it, due to the low motion in your garden video, you might be able to do HD Periscope (1280x720) instead of SD (960x540)

**Comment by scivision** [comment]
Does a shell command like from this script work?
https://github.com/ppihus/rtsp-stream-to-youtube

**Comment by sbonaime** [comment]
@scivision 
Hi ! Can you re open this issue ? I would like to stream an rtsp source to youtube and twitch. Here is the command line I use 

    ffmpeg -rtsp_transport tcp 
                -i rtsp://admin:@rtsp_IP:554 \
                -q:v 1 -c:v libx264    -c:a aac -ab 44.1k -crf 25\
                -f flv rtmp://a.rtmp.youtube.com/live2/Xxxxx-xxxx-xx
