### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by TorchwoodPL** [scivision/PyLivestream#23]
Hi,

 when I use command:
./Glob /home/disk/obs/Trailers twitch -glob "*.mp4" -loop -shuffle

Is there a way to stream without ceating new stream every new mp4 file?

TIA

**Comment by scivision** [comment]
@TorchwoodPL not that I know of, without using more tricks with FFmpeg. This was designed as a very basic tool for me to do livestreams with nothing more than pure Python and FFmpeg, so what happens is that there is a glitch in the stream every time a new files starts.

In particular, this file streaming case is not one used by me, but I only made it because of user request.
