### ISSUE TITLE
[RFE]: detect if PulseAudio not available and error

### ISSUE THREAD

**Issue by dinki** [scivision/PyLivestream#36]
First let me thank you for providing this project.  It looks like exactly what I'm wanting.  Unfortunately I'm having problems getting this going and perhaps someone can help.

Raspberry Pi Zero W running Rasbian Buster
Linux sign1 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux

$ python --version
Python 3.7.3

$ ffmpeg --version
ffmpeg version 4.1.4-1+rpt1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers

Here's the error:

```
$ WebcamLivestream --yes facebook
going live on ['facebook']

 /usr/bin/ffmpeg -loglevel error -y -f v4l2 -i /dev/video0 -f pulse -i default -codec:v libx264 -pix_fmt yuv420p -preset veryfast -b:v 500k -g 60 -codec:a aac -b:a 128k -ar 44100 -maxrate 500k -bufsize 250k -strict experimental -f flv rtmps://live-api-s.facebook.com:443/rtmp/111103643332502?s_bl=1&s_ps=1&s_sw=0&s_vt=api-s&a=AbzwuWpQlJ3859ds

default: No such process
```

I've tried and tried to upgrade my ffmpeg to 4.2 but I am not able to figure out how to do this.  I'm guessing this is probably the problem?  I've downloaded countless binaries for armhf and armel and all result in seg faults.  I've tried compiling from source but I keep getting errors.

Do you know of anyone running PyLivestream on a Raspberry Pi Zero?  Any ideas on what I might do to get this going?

**Comment by scivision** [comment]
PulseAudio might not be running on the Pi Zero, assuming you're using Raspbian Lite. As seen in the .info file from http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-09-30/, pulseaudio is not installed by default. The command line above indicates `-f pulse -i default` which is trying to use PulseAudio.

Based on https://ffmpeg.org/ffmpeg-devices.html#alsa I would try replacing `-f pulse -i default` with something like `-f alsa -i hw:0`.

This is something that would probably be good for PyLivestream to check and give a minimal error about, rather than the confusing message from FFmpeg. Thanks for letting us know.

**Comment by scivision** [comment]
Also I would specifically try the simple command like:

```sh
ffmpeg -f alsa -i hw:0 alsaout.wav
```

to see if alsaout.wav writes and has the expected audio content.

**Comment by dinki** [comment]
Thanks for taking the time out to work with me on this.  I tried the ffmpeg command you suggested and I get this output:

```
[alsa @ 0x143fe40] cannot open audio device hw:0 (No such file or directory)
hw:0: Input/output error

```

**Comment by scivision** [comment]
OK so I'm guessing that your webcam has a built-in microphone and that you can see / hear / record the output from the webcam to a file with another program. This is not a configuration I've tried recently. However I do think it's a configuration that is of general interest--for example, setting up a garden or garage webcam with Pi Zero.

I have done such things in the past, and had to modify .asoundrc and the like. However, I don't have the time to try this out in the near future, despite it being interesting.

One thing to consider, the possible frame rate and resolution will be much lower in general using a webcam with the Pi Zero because the webcam will use a lot of CPU. While the PiCamera module uses the GPU and so you can get HD resolution and 30+ fps frame rate.

**Comment by dinki** [comment]
I should have been more descriptive in my original post.  This is using a RPi camera module and not an external web cam.  To the best of my knowledge, this camera does not have audio.  My eventual goal is to connect a bluetooth microphone via the built in bluetooth.

Do I need to set up an audio source for PyLivestream to work?

**Comment by scivision** [comment]
OK, in that case just omit the audio part, as is done by having a blank audio_fps as you noted.

However--I don't think most streaming services will allow no audio stream.  I think what would be needed is an audio stream with a null input, just so there is an audio stream output, even though it has no content.

**Comment by dinki** [comment]
Hmm.  I'm far from a linux expert.  May be easier for me to figure out a real audio source rather than figuring out how to fake one.

**Comment by scivision** [comment]
Try the current revision of Pylivestream:

```sh
git pull
```

41c5bb5 is the revision. I don't have a Pi Zero at hand at the moment, but this tries to do it.

Oh yes, also in your pylivestream.ini, set `audiochan: null`

**Comment by scivision** [comment]
I think to detect all the various audio libraries might not be feasible for PyLivestream. FFmpeg will generally try to give some information in its error message, as even FFmpeg might not know exactly what's wrong.
