### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by leothewolf** [scivision/PyLivestream#79]
Hey there I have been through all the stuff I mean the whole repo but I am not able to use it for my purpose Ill define my purpose here can you pls help make out a code out of it:

So I wanna play a video which is 11hr long on my youtube channel which is store in D:\ and every time it ends I wanna replay it or put it on loop, can someone pls tell me the exact code I should put in a .py file?

**Comment by leothewolf** [comment]
Yes the command would be like:
```sh
FileGlobLivestream /home/user/myaudio youtube -glob "*.mp3" -image /home/user/pictures/myimg.png
```

_Originally posted by @scivision in https://github.com/scivision/PyLivestream/issues/20#issuecomment-458217040_

I found this thing in issues but how exactly to use it?

**Comment by tabanger** [comment]
You need to install Python on your Windows machine, and then install PyLivestream.  Since it's Windows, you probably also need to install ffmpeg.

After that, you configure pylivestream.ini file with your YouTube key.  Then you can run the following command at the command-line to endlessly loop your video file:

`FileLoopLivestream D:\path\to\videofile.mp4 youtube`

**Comment by leothewolf** [comment]
> You need to install Python on your Windows machine, and then install PyLivestream. Since it's Windows, you probably also need to install ffmpeg.
> 
> After that, you configure pylivestream.ini file with your YouTube key. Then you can run the following command at the command-line to endlessly loop your video file:
> 
> `FileLoopLivestream D:\path\to\videofile.mp4 youtube`

Aha got it working thanks a lot man!!May god bless you!!
